# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geopunt4qgisParcel.ui'
#
# Created: Mon Nov 10 14:52:08 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_geopunt4QgisParcelDlg(object):
    def setupUi(self, geopunt4QgisParcelDlg):
        geopunt4QgisParcelDlg.setObjectName(_fromUtf8("geopunt4QgisParcelDlg"))
        geopunt4QgisParcelDlg.resize(468, 232)
        geopunt4QgisParcelDlg.setMaximumSize(QtCore.QSize(900, 232))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geopunt4Qgis/images/geopuntParcelSmall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        geopunt4QgisParcelDlg.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(geopunt4QgisParcelDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.parcelWgt = QtGui.QWidget(geopunt4QgisParcelDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parcelWgt.sizePolicy().hasHeightForWidth())
        self.parcelWgt.setSizePolicy(sizePolicy)
        self.parcelWgt.setObjectName(_fromUtf8("parcelWgt"))
        self.gridLayout = QtGui.QGridLayout(self.parcelWgt)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.departmentLbl = QtGui.QLabel(self.parcelWgt)
        self.departmentLbl.setObjectName(_fromUtf8("departmentLbl"))
        self.gridLayout.addWidget(self.departmentLbl, 2, 0, 1, 3)
        self.ZoomKnop_muni = QtGui.QPushButton(self.parcelWgt)
        self.ZoomKnop_muni.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geopunt4Qgis/images/binocularsSmall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZoomKnop_muni.setIcon(icon1)
        self.ZoomKnop_muni.setAutoDefault(False)
        self.ZoomKnop_muni.setFlat(False)
        self.ZoomKnop_muni.setObjectName(_fromUtf8("ZoomKnop_muni"))
        self.gridLayout.addWidget(self.ZoomKnop_muni, 1, 4, 1, 1)
        self.sectionLbl = QtGui.QLabel(self.parcelWgt)
        self.sectionLbl.setObjectName(_fromUtf8("sectionLbl"))
        self.gridLayout.addWidget(self.sectionLbl, 4, 0, 1, 1)
        self.departmentCbx = QtGui.QComboBox(self.parcelWgt)
        self.departmentCbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departmentCbx.sizePolicy().hasHeightForWidth())
        self.departmentCbx.setSizePolicy(sizePolicy)
        self.departmentCbx.setEditable(True)
        self.departmentCbx.setObjectName(_fromUtf8("departmentCbx"))
        self.gridLayout.addWidget(self.departmentCbx, 3, 1, 1, 3)
        self.parcelCbx = QtGui.QComboBox(self.parcelWgt)
        self.parcelCbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parcelCbx.sizePolicy().hasHeightForWidth())
        self.parcelCbx.setSizePolicy(sizePolicy)
        self.parcelCbx.setEditable(True)
        self.parcelCbx.setObjectName(_fromUtf8("parcelCbx"))
        self.gridLayout.addWidget(self.parcelCbx, 7, 1, 1, 3)
        self.municipalityLbl = QtGui.QLabel(self.parcelWgt)
        self.municipalityLbl.setObjectName(_fromUtf8("municipalityLbl"))
        self.gridLayout.addWidget(self.municipalityLbl, 0, 0, 1, 2)
        self.municipalityCbx = QtGui.QComboBox(self.parcelWgt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.municipalityCbx.sizePolicy().hasHeightForWidth())
        self.municipalityCbx.setSizePolicy(sizePolicy)
        self.municipalityCbx.setEditable(True)
        self.municipalityCbx.setObjectName(_fromUtf8("municipalityCbx"))
        self.gridLayout.addWidget(self.municipalityCbx, 1, 1, 1, 3)
        self.ZoomKnop_dep = QtGui.QPushButton(self.parcelWgt)
        self.ZoomKnop_dep.setText(_fromUtf8(""))
        self.ZoomKnop_dep.setIcon(icon1)
        self.ZoomKnop_dep.setAutoDefault(False)
        self.ZoomKnop_dep.setFlat(False)
        self.ZoomKnop_dep.setObjectName(_fromUtf8("ZoomKnop_dep"))
        self.gridLayout.addWidget(self.ZoomKnop_dep, 3, 4, 1, 1)
        self.ZoomKnop_sect = QtGui.QPushButton(self.parcelWgt)
        self.ZoomKnop_sect.setText(_fromUtf8(""))
        self.ZoomKnop_sect.setIcon(icon1)
        self.ZoomKnop_sect.setAutoDefault(False)
        self.ZoomKnop_sect.setFlat(False)
        self.ZoomKnop_sect.setObjectName(_fromUtf8("ZoomKnop_sect"))
        self.gridLayout.addWidget(self.ZoomKnop_sect, 5, 4, 1, 1)
        self.ZoomKnop_parcel = QtGui.QPushButton(self.parcelWgt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomKnop_parcel.sizePolicy().hasHeightForWidth())
        self.ZoomKnop_parcel.setSizePolicy(sizePolicy)
        self.ZoomKnop_parcel.setText(_fromUtf8(""))
        self.ZoomKnop_parcel.setIcon(icon1)
        self.ZoomKnop_parcel.setAutoDefault(False)
        self.ZoomKnop_parcel.setFlat(False)
        self.ZoomKnop_parcel.setObjectName(_fromUtf8("ZoomKnop_parcel"))
        self.gridLayout.addWidget(self.ZoomKnop_parcel, 7, 4, 1, 1)
        self.sectionCbx = QtGui.QComboBox(self.parcelWgt)
        self.sectionCbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionCbx.sizePolicy().hasHeightForWidth())
        self.sectionCbx.setSizePolicy(sizePolicy)
        self.sectionCbx.setEditable(True)
        self.sectionCbx.setObjectName(_fromUtf8("sectionCbx"))
        self.gridLayout.addWidget(self.sectionCbx, 5, 1, 1, 3)
        self.parcelLbl = QtGui.QLabel(self.parcelWgt)
        self.parcelLbl.setObjectName(_fromUtf8("parcelLbl"))
        self.gridLayout.addWidget(self.parcelLbl, 6, 0, 1, 3)
        self.verticalLayout.addWidget(self.parcelWgt)
        self.widgetBtnsLayout = QtGui.QHBoxLayout()
        self.widgetBtnsLayout.setObjectName(_fromUtf8("widgetBtnsLayout"))
        self.saveBtn = QtGui.QPushButton(geopunt4QgisParcelDlg)
        self.saveBtn.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geopunt4Qgis/images/addPointLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon2)
        self.saveBtn.setAutoDefault(False)
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))
        self.widgetBtnsLayout.addWidget(self.saveBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.widgetBtnsLayout.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(geopunt4QgisParcelDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.widgetBtnsLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.widgetBtnsLayout)

        self.retranslateUi(geopunt4QgisParcelDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), geopunt4QgisParcelDlg.close)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), geopunt4QgisParcelDlg.close)
        QtCore.QMetaObject.connectSlotsByName(geopunt4QgisParcelDlg)

    def retranslateUi(self, geopunt4QgisParcelDlg):
        geopunt4QgisParcelDlg.setWindowTitle(_translate("geopunt4QgisParcelDlg", "Zoek een perceel via Geopunt ", None))
        self.departmentLbl.setText(_translate("geopunt4QgisParcelDlg", "Departement:", None))
        self.ZoomKnop_muni.setToolTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_muni.setStatusTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.sectionLbl.setText(_translate("geopunt4QgisParcelDlg", "Sectie:", None))
        self.municipalityLbl.setText(_translate("geopunt4QgisParcelDlg", "Gemeente:", None))
        self.ZoomKnop_dep.setToolTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_dep.setStatusTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_sect.setToolTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_sect.setStatusTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_parcel.setToolTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.ZoomKnop_parcel.setStatusTip(_translate("geopunt4QgisParcelDlg", "Zoom naar", None))
        self.parcelLbl.setText(_translate("geopunt4QgisParcelDlg", "Perceelnummer:", None))
        self.saveBtn.setText(_translate("geopunt4QgisParcelDlg", "Toevoegen aan kaart", None))

import resources_rc
